// Mocks generated by Mockito 5.4.0 from annotations
// in field/test/data/repositary/project_list/project_list_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:field/data/model/popupdata_vo.dart' as _i6;
import 'package:field/data/model/project_vo.dart' as _i5;
import 'package:field/data/model/sync_size_vo.dart' as _i7;
import 'package:field/data/repository/project_list/project_list_repository.dart'
    as _i3;
import 'package:field/networking/network_response.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<Model> extends _i1.SmartFake implements _i2.Result<Model> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProjectListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectListRepository extends _i1.Mock
    implements _i3.ProjectListRepository {
  MockProjectListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Project>> getProjectList(
    int? page,
    int? batchSize,
    Map<String, dynamic>? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProjectList,
          [
            page,
            batchSize,
            request,
          ],
        ),
        returnValue: _i4.Future<List<_i5.Project>>.value(<_i5.Project>[]),
      ) as _i4.Future<List<_i5.Project>>);
  @override
  _i4.Future<List<_i6.Popupdata>> getPopupDataList(
    int? page,
    int? batchSize,
    Map<String, dynamic>? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopupDataList,
          [
            page,
            batchSize,
            request,
          ],
        ),
        returnValue: _i4.Future<List<_i6.Popupdata>>.value(<_i6.Popupdata>[]),
      ) as _i4.Future<List<_i6.Popupdata>>);
  @override
  _i4.Future<List<_i5.Project>> getWorkspaceList(
          Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkspaceList,
          [request],
        ),
        returnValue: _i4.Future<List<_i5.Project>>.value(<_i5.Project>[]),
      ) as _i4.Future<List<_i5.Project>>);
  @override
  _i4.Future<dynamic> setFavProject(Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFavProject,
          [request],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);
  @override
  _i4.Future<_i2.Result<dynamic>> getProjectAndLocationList(
          Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProjectAndLocationList,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Result<dynamic>>.value(_FakeResult_0<dynamic>(
          this,
          Invocation.method(
            #getProjectAndLocationList,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Result<dynamic>>);
  @override
  _i4.Future<_i2.Result<dynamic>> getColumnHeaderList(
          Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getColumnHeaderList,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Result<dynamic>>.value(_FakeResult_0<dynamic>(
          this,
          Invocation.method(
            #getColumnHeaderList,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Result<dynamic>>);
  @override
  _i4.Future<_i2.Result<dynamic>> getFormList(Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFormList,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Result<dynamic>>.value(_FakeResult_0<dynamic>(
          this,
          Invocation.method(
            #getFormList,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Result<dynamic>>);
  @override
  _i4.Future<_i2.Result<dynamic>> getFormMessageBatchList(
          Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFormMessageBatchList,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Result<dynamic>>.value(_FakeResult_0<dynamic>(
          this,
          Invocation.method(
            #getFormMessageBatchList,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Result<dynamic>>);
  @override
  _i4.Future<_i2.Result<dynamic>> downloadFormAttachmentInBatch(
    Map<String, dynamic>? request, {
    bool? bAkamaiDownload = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFormAttachmentInBatch,
          [request],
          {#bAkamaiDownload: bAkamaiDownload},
        ),
        returnValue:
            _i4.Future<_i2.Result<dynamic>>.value(_FakeResult_0<dynamic>(
          this,
          Invocation.method(
            #downloadFormAttachmentInBatch,
            [request],
            {#bAkamaiDownload: bAkamaiDownload},
          ),
        )),
      ) as _i4.Future<_i2.Result<dynamic>>);
  @override
  _i4.Future<_i2.Result<dynamic>> getServerTime(
          Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getServerTime,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Result<dynamic>>.value(_FakeResult_0<dynamic>(
          this,
          Invocation.method(
            #getServerTime,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Result<dynamic>>);
  @override
  _i4.Future<_i2.Result<dynamic>> getHashedValue(
          Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHashedValue,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Result<dynamic>>.value(_FakeResult_0<dynamic>(
          this,
          Invocation.method(
            #getHashedValue,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Result<dynamic>>);
  @override
  _i4.Future<_i2.Result<dynamic>> getStatusStyle(
          Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatusStyle,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Result<dynamic>>.value(_FakeResult_0<dynamic>(
          this,
          Invocation.method(
            #getStatusStyle,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Result<dynamic>>);
  @override
  _i4.Future<_i2.Result<dynamic>> getManageTypeList(
          Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getManageTypeList,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Result<dynamic>>.value(_FakeResult_0<dynamic>(
          this,
          Invocation.method(
            #getManageTypeList,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Result<dynamic>>);
  @override
  _i4.Future<List<_i7.SyncSizeVo>> deleteItemFromSyncTable(
          Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteItemFromSyncTable,
          [request],
        ),
        returnValue: _i4.Future<List<_i7.SyncSizeVo>>.value(<_i7.SyncSizeVo>[]),
      ) as _i4.Future<List<_i7.SyncSizeVo>>);
}
