package com.asite.field.models

data class ObservationData(
    val annotationId: String,
    val appBuilderID: String,
    val appType: Int,
    val commId: String,
    val coordinates: String,
    val creatorOrgName: String,
    val creatorUserName: String,
    val folderId: String,
    val formCode: String,
    val formCreationDate: String,
    val formDueDays: Int,
    val formId: String,
    val formTitle: String,
    val formTypeCode: String,
    val formTypeId: String,
    val generateURI: Boolean,
    val hasAttachment: Boolean,
    val isActive: Boolean,
    val isSyncIndexUpdate: Boolean,
    val locationDetailVO: LocationDetailVO,
    val locationId: Long,
    val msgId: String,
    val observationId: Long,
    val pageNumber: Int,
    val projectId: String,
    val recipientList: List<Recipient>,
    val revisionId: String,
    val statusVO: StatusVO?,
    val templateType: Int,
    var pinWidth: Double = 0.0,
    var pinHeight: Double = 0.0,
)